export const SET_COORDS = 'SET_COORDS';
export const SET_FORECAST = 'SET_FORECAST';
export const TOGGLE_TEMPERATURE_UNIT = 'TOGGLE_TEMPERATURE_UNIT';
export const TOGGLE_CITY_INPUT = 'TOGGLE_CITY_INPUT';
export const SET_CITIES_LIST = 'SET_CITIES_LIST';

export const FETCH_FORECAST = 'FETCH_FORECAST';
export const FETCH_LIST_OF_CITIES = 'FETCH_LIST_OF_CITIES';

// Countdown types
export const START_COUNTDOWN = 'START_COUNTDOWN';
export const UPDATE_COUNTDOWN = 'UPDATE_COUNTDOWN';
export const RESET_COUNTDOWN = 'RESET_COUNTDOWN';
